### ISSUE TITLE
Volume initialization failed

### ISSUE THREAD

**Issue by Alig1493** [DanWahlin/DockerAndKubernetesCourseCode#21]
Hello,

I came across a bug where the PV fails to find the path set [here](https://github.com/DanWahlin/DockerAndKubernetesCourseCode/blob/main/samples/volumes/pv-pvc-sc-cm/mongo.deployment.yml#L57), despite following the instructions in the readme to create and assign path accordingly.

I'm using a Ubuntu x86_64 OS and running minikube as the primary tool to create pods and containers.

Thanks.

**Comment by DanWahlin** [comment]
Hi Mohammed. This particular sample is geared toward Docker Desktop on Windows and Mac as mentioned in the yaml comments. A linux path is listed in the readme purely for the sake of example (it's not the focus of this sample though), but there would likely be additional security requirements to be implemented on the directory and the nodeAffinity (used in the PV) wouldn't apply since it's geared toward Docker Desktop. 

I don't have a version that's been run with minikube on Linux unfortunately and don't know if minikube has any additional requirements for that. I suspect someone has documented or posted about that particular setup. If I come across anything I'll update this comment (please do the same if you find anything). In doing a quick search I did come across the following document which might get you pointed in the right direction for using persistent volumes with minikube.

https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/

**Comment by DanWahlin** [comment]
Closing since this is an old issue with no additional responses.
